### ISSUE TITLE
Permission non accordée: '/tmp\\LiveboxMonitor_state'

### ISSUE THREAD

**Issue by solsticedhiver** [p-dor/LiveboxMonitor#16]
Sous Linux (ubuntu 22.04), j'ai droit à:

```
$ python LiveboxMonitor.py 
No or wrong configuration file, creating one.
Auth error {"status":1,"data":{}}
Authentification failed.
Traceback (most recent call last):
  File "/home/test/Téléchargements/LiveboxMonitor-0.9.4/LiveboxMonitor.py", line 262, in <module>
    aUI = LiveboxMonitorUI()
  File "/home/test/Téléchargements/LiveboxMonitor-0.9.4/LiveboxMonitor.py", line 68, in __init__
    if self.signin():
  File "/home/test/Téléchargements/LiveboxMonitor-0.9.4/LiveboxMonitor.py", line 151, in signin
    r = self._session.signin()
  File "/home/test/Téléchargements/LiveboxMonitor-0.9.4/src/LmSession.py", line 84, in signin
    with open(aStateFilePath, 'wb') as f:
PermissionError: [Errno 13] Permission non accordée: '/tmp\\LiveboxMonitor_state'

```

Un fix rapide a consisté à modifier `src/LmSession.py` ligne 39 pour utiliser `os.sep` qui le séparateur "universel" qq soit la plateforme utilisée au lieu de hardcodé '\\\\'

**Comment by p-dor** [comment]
Bonsoir, essayez avec la dernière release (0.9.7), ce problème est fixé depuis un moment. Vous avez du prendre la version pointée par l'article de Korben mais cette release datait un peu, et beaucoup de fonctionnalités ont été rajoutées depuis ;-)

**Comment by solsticedhiver** [comment]
oops. pour une fois que je prends pas la version git directe. désolé /o\
