### ISSUE TITLE
Fonctionne sous Linux avec une mini modification

### ISSUE THREAD

**Issue by ctotof38** [p-dor/LiveboxMonitor#6]
Bonjour,
la version 0.9.4 (récupéré à partir du zip) plante sur Linux avec l'erreur suivante : 
```
Traceback (most recent call last):
  File "/home/xuborange/LiveboxMonitor-0.9.4/LiveboxMonitor.py", line 262, in <module>
    aUI = LiveboxMonitorUI()
  File "/home/xuborange/LiveboxMonitor-0.9.4/LiveboxMonitor.py", line 68, in __init__
    if self.signin():
  File "/home/xuborange/LiveboxMonitor-0.9.4/LiveboxMonitor.py", line 151, in signin
    r = self._session.signin()
  File "/home/xuborange/LiveboxMonitor-0.9.4/src/LmSession.py", line 86, in signin
    with open(aStateFilePath, 'wb') as f:
PermissionError: [Errno 13] Permission non accordée: '/tmp\\LiveboxMonitor_state'
```
En fait, il suffit de remplacer dans le fichier LmSession.py la ligne qui fabrique le chemin du fichier d'état
```
aStateFilePath = tempfile.gettempdir() + '\\' + self._name + '_state'
```
Par
```
import os.path
...
aStateFilePath = os.path.join(tempfile.gettempdir(), self._name + '_state')
```
Cela fabrique un chemin compatible avec l'OS.
Et quelle belle interface...

**Comment by ctotof38** [comment]
Args, je n'avais pas vu le 0.9.7. Bravo pour le travail

**Comment by p-dor** [comment]
Merci ! Et puis vous avez bien fait de repartir sur la 0.9.7, il y a eu du chemin depuis la 0.9.4 ;-)
